package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class AuthortestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public AuthortestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAuthortestidIsNull() {
            addCriterion("authortestid is null");
            return (Criteria) this;
        }

        public Criteria andAuthortestidIsNotNull() {
            addCriterion("authortestid is not null");
            return (Criteria) this;
        }

        public Criteria andAuthortestidEqualTo(Integer value) {
            addCriterion("authortestid =", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidNotEqualTo(Integer value) {
            addCriterion("authortestid <>", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidGreaterThan(Integer value) {
            addCriterion("authortestid >", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidGreaterThanOrEqualTo(Integer value) {
            addCriterion("authortestid >=", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidLessThan(Integer value) {
            addCriterion("authortestid <", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidLessThanOrEqualTo(Integer value) {
            addCriterion("authortestid <=", value, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidIn(List<Integer> values) {
            addCriterion("authortestid in", values, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidNotIn(List<Integer> values) {
            addCriterion("authortestid not in", values, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidBetween(Integer value1, Integer value2) {
            addCriterion("authortestid between", value1, value2, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthortestidNotBetween(Integer value1, Integer value2) {
            addCriterion("authortestid not between", value1, value2, "authortestid");
            return (Criteria) this;
        }

        public Criteria andAuthornameIsNull() {
            addCriterion("authorname is null");
            return (Criteria) this;
        }

        public Criteria andAuthornameIsNotNull() {
            addCriterion("authorname is not null");
            return (Criteria) this;
        }

        public Criteria andAuthornameEqualTo(String value) {
            addCriterion("authorname =", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotEqualTo(String value) {
            addCriterion("authorname <>", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameGreaterThan(String value) {
            addCriterion("authorname >", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameGreaterThanOrEqualTo(String value) {
            addCriterion("authorname >=", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLessThan(String value) {
            addCriterion("authorname <", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLessThanOrEqualTo(String value) {
            addCriterion("authorname <=", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameLike(String value) {
            addCriterion("authorname like", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotLike(String value) {
            addCriterion("authorname not like", value, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameIn(List<String> values) {
            addCriterion("authorname in", values, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotIn(List<String> values) {
            addCriterion("authorname not in", values, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameBetween(String value1, String value2) {
            addCriterion("authorname between", value1, value2, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthornameNotBetween(String value1, String value2) {
            addCriterion("authorname not between", value1, value2, "authorname");
            return (Criteria) this;
        }

        public Criteria andAuthorimgIsNull() {
            addCriterion("authorimg is null");
            return (Criteria) this;
        }

        public Criteria andAuthorimgIsNotNull() {
            addCriterion("authorimg is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorimgEqualTo(String value) {
            addCriterion("authorimg =", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgNotEqualTo(String value) {
            addCriterion("authorimg <>", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgGreaterThan(String value) {
            addCriterion("authorimg >", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgGreaterThanOrEqualTo(String value) {
            addCriterion("authorimg >=", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgLessThan(String value) {
            addCriterion("authorimg <", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgLessThanOrEqualTo(String value) {
            addCriterion("authorimg <=", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgLike(String value) {
            addCriterion("authorimg like", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgNotLike(String value) {
            addCriterion("authorimg not like", value, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgIn(List<String> values) {
            addCriterion("authorimg in", values, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgNotIn(List<String> values) {
            addCriterion("authorimg not in", values, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgBetween(String value1, String value2) {
            addCriterion("authorimg between", value1, value2, "authorimg");
            return (Criteria) this;
        }

        public Criteria andAuthorimgNotBetween(String value1, String value2) {
            addCriterion("authorimg not between", value1, value2, "authorimg");
            return (Criteria) this;
        }

        public Criteria andOutytypnumIsNull() {
            addCriterion("outytypnum is null");
            return (Criteria) this;
        }

        public Criteria andOutytypnumIsNotNull() {
            addCriterion("outytypnum is not null");
            return (Criteria) this;
        }

        public Criteria andOutytypnumEqualTo(Integer value) {
            addCriterion("outytypnum =", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumNotEqualTo(Integer value) {
            addCriterion("outytypnum <>", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumGreaterThan(Integer value) {
            addCriterion("outytypnum >", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("outytypnum >=", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumLessThan(Integer value) {
            addCriterion("outytypnum <", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumLessThanOrEqualTo(Integer value) {
            addCriterion("outytypnum <=", value, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumIn(List<Integer> values) {
            addCriterion("outytypnum in", values, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumNotIn(List<Integer> values) {
            addCriterion("outytypnum not in", values, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumBetween(Integer value1, Integer value2) {
            addCriterion("outytypnum between", value1, value2, "outytypnum");
            return (Criteria) this;
        }

        public Criteria andOutytypnumNotBetween(Integer value1, Integer value2) {
            addCriterion("outytypnum not between", value1, value2, "outytypnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authortest
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}