package com.zyx.mybookstore.Pojo;

public class Authortest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authortest.authortestid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private Integer authortestid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authortest.authorname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String authorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authortest.authorimg
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String authorimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authortest.outytypnum
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private Integer outytypnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authortest.authorbrief
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String authorbrief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authortest.authortestid
     *
     * @return the value of authortest.authortestid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Integer getAuthortestid() {
        return authortestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authortest.authortestid
     *
     * @param authortestid the value for authortest.authortestid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setAuthortestid(Integer authortestid) {
        this.authortestid = authortestid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authortest.authorname
     *
     * @return the value of authortest.authorname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getAuthorname() {
        return authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authortest.authorname
     *
     * @param authorname the value for authortest.authorname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setAuthorname(String authorname) {
        this.authorname = authorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authortest.authorimg
     *
     * @return the value of authortest.authorimg
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getAuthorimg() {
        return authorimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authortest.authorimg
     *
     * @param authorimg the value for authortest.authorimg
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setAuthorimg(String authorimg) {
        this.authorimg = authorimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authortest.outytypnum
     *
     * @return the value of authortest.outytypnum
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Integer getOutytypnum() {
        return outytypnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authortest.outytypnum
     *
     * @param outytypnum the value for authortest.outytypnum
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setOutytypnum(Integer outytypnum) {
        this.outytypnum = outytypnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authortest.authorbrief
     *
     * @return the value of authortest.authorbrief
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getAuthorbrief() {
        return authorbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authortest.authorbrief
     *
     * @param authorbrief the value for authortest.authorbrief
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setAuthorbrief(String authorbrief) {
        this.authorbrief = authorbrief;
    }
}