package com.zyx.mybookstore.Pojo;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookbrief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookoldprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Double bookoldprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.booknewprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Double booknewprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookauthor
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookauthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookclass1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookclass1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookclass2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookclass2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookclass3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookclass3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookpress
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookpress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookpresstime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookpresstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.booksize
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String booksize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookisbn
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookisbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book2class1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String book2class1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book2class2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String book2class2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book2class3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String book2class3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookid
     *
     * @return the value of book.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookid
     *
     * @param bookid the value for book.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookbrief
     *
     * @return the value of book.bookbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookbrief() {
        return bookbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookbrief
     *
     * @param bookbrief the value for book.bookbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookbrief(String bookbrief) {
        this.bookbrief = bookbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookoldprice
     *
     * @return the value of book.bookoldprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Double getBookoldprice() {
        return bookoldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookoldprice
     *
     * @param bookoldprice the value for book.bookoldprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookoldprice(Double bookoldprice) {
        this.bookoldprice = bookoldprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.booknewprice
     *
     * @return the value of book.booknewprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Double getBooknewprice() {
        return booknewprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.booknewprice
     *
     * @param booknewprice the value for book.booknewprice
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBooknewprice(Double booknewprice) {
        this.booknewprice = booknewprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookauthor
     *
     * @return the value of book.bookauthor
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookauthor() {
        return bookauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookauthor
     *
     * @param bookauthor the value for book.bookauthor
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookauthor(String bookauthor) {
        this.bookauthor = bookauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookclass1
     *
     * @return the value of book.bookclass1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookclass1() {
        return bookclass1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookclass1
     *
     * @param bookclass1 the value for book.bookclass1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookclass1(String bookclass1) {
        this.bookclass1 = bookclass1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookclass2
     *
     * @return the value of book.bookclass2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookclass2() {
        return bookclass2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookclass2
     *
     * @param bookclass2 the value for book.bookclass2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookclass2(String bookclass2) {
        this.bookclass2 = bookclass2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookclass3
     *
     * @return the value of book.bookclass3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookclass3() {
        return bookclass3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookclass3
     *
     * @param bookclass3 the value for book.bookclass3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookclass3(String bookclass3) {
        this.bookclass3 = bookclass3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookpress
     *
     * @return the value of book.bookpress
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookpress() {
        return bookpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookpress
     *
     * @param bookpress the value for book.bookpress
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookpress(String bookpress) {
        this.bookpress = bookpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookpresstime
     *
     * @return the value of book.bookpresstime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookpresstime() {
        return bookpresstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookpresstime
     *
     * @param bookpresstime the value for book.bookpresstime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookpresstime(String bookpresstime) {
        this.bookpresstime = bookpresstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.booksize
     *
     * @return the value of book.booksize
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBooksize() {
        return booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.booksize
     *
     * @param booksize the value for book.booksize
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBooksize(String booksize) {
        this.booksize = booksize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookimg
     *
     * @return the value of book.bookimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookimg() {
        return bookimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookimg
     *
     * @param bookimg the value for book.bookimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookimg(String bookimg) {
        this.bookimg = bookimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookisbn
     *
     * @return the value of book.bookisbn
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookisbn() {
        return bookisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookisbn
     *
     * @param bookisbn the value for book.bookisbn
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookisbn(String bookisbn) {
        this.bookisbn = bookisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookinfo
     *
     * @return the value of book.bookinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookinfo() {
        return bookinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookinfo
     *
     * @param bookinfo the value for book.bookinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookinfo(Integer bookinfo) {
        this.bookinfo = bookinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book2class1
     *
     * @return the value of book.book2class1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBook2class1() {
        return book2class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book2class1
     *
     * @param book2class1 the value for book.book2class1
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBook2class1(String book2class1) {
        this.book2class1 = book2class1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book2class2
     *
     * @return the value of book.book2class2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBook2class2() {
        return book2class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book2class2
     *
     * @param book2class2 the value for book.book2class2
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBook2class2(String book2class2) {
        this.book2class2 = book2class2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book2class3
     *
     * @return the value of book.book2class3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBook2class3() {
        return book2class3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book2class3
     *
     * @param book2class3 the value for book.book2class3
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBook2class3(String book2class3) {
        this.book2class3 = book2class3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookcount
     *
     * @return the value of book.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookcount() {
        return bookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookcount
     *
     * @param bookcount the value for book.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookcount(Integer bookcount) {
        this.bookcount = bookcount;
    }
}