package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class BookExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public BookExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBookidIsNull() {
            addCriterion("bookid is null");
            return (Criteria) this;
        }

        public Criteria andBookidIsNotNull() {
            addCriterion("bookid is not null");
            return (Criteria) this;
        }

        public Criteria andBookidEqualTo(Integer value) {
            addCriterion("bookid =", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotEqualTo(Integer value) {
            addCriterion("bookid <>", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThan(Integer value) {
            addCriterion("bookid >", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookid >=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThan(Integer value) {
            addCriterion("bookid <", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThanOrEqualTo(Integer value) {
            addCriterion("bookid <=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidIn(List<Integer> values) {
            addCriterion("bookid in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotIn(List<Integer> values) {
            addCriterion("bookid not in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidBetween(Integer value1, Integer value2) {
            addCriterion("bookid between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotBetween(Integer value1, Integer value2) {
            addCriterion("bookid not between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNull() {
            addCriterion("bookname is null");
            return (Criteria) this;
        }

        public Criteria andBooknameIsNotNull() {
            addCriterion("bookname is not null");
            return (Criteria) this;
        }

        public Criteria andBooknameEqualTo(String value) {
            addCriterion("bookname =", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotEqualTo(String value) {
            addCriterion("bookname <>", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThan(String value) {
            addCriterion("bookname >", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameGreaterThanOrEqualTo(String value) {
            addCriterion("bookname >=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThan(String value) {
            addCriterion("bookname <", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLessThanOrEqualTo(String value) {
            addCriterion("bookname <=", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameLike(String value) {
            addCriterion("bookname like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotLike(String value) {
            addCriterion("bookname not like", value, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameIn(List<String> values) {
            addCriterion("bookname in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotIn(List<String> values) {
            addCriterion("bookname not in", values, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameBetween(String value1, String value2) {
            addCriterion("bookname between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andBooknameNotBetween(String value1, String value2) {
            addCriterion("bookname not between", value1, value2, "bookname");
            return (Criteria) this;
        }

        public Criteria andBookbriefIsNull() {
            addCriterion("bookbrief is null");
            return (Criteria) this;
        }

        public Criteria andBookbriefIsNotNull() {
            addCriterion("bookbrief is not null");
            return (Criteria) this;
        }

        public Criteria andBookbriefEqualTo(String value) {
            addCriterion("bookbrief =", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefNotEqualTo(String value) {
            addCriterion("bookbrief <>", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefGreaterThan(String value) {
            addCriterion("bookbrief >", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefGreaterThanOrEqualTo(String value) {
            addCriterion("bookbrief >=", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefLessThan(String value) {
            addCriterion("bookbrief <", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefLessThanOrEqualTo(String value) {
            addCriterion("bookbrief <=", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefLike(String value) {
            addCriterion("bookbrief like", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefNotLike(String value) {
            addCriterion("bookbrief not like", value, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefIn(List<String> values) {
            addCriterion("bookbrief in", values, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefNotIn(List<String> values) {
            addCriterion("bookbrief not in", values, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefBetween(String value1, String value2) {
            addCriterion("bookbrief between", value1, value2, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookbriefNotBetween(String value1, String value2) {
            addCriterion("bookbrief not between", value1, value2, "bookbrief");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceIsNull() {
            addCriterion("bookoldprice is null");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceIsNotNull() {
            addCriterion("bookoldprice is not null");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceEqualTo(Double value) {
            addCriterion("bookoldprice =", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceNotEqualTo(Double value) {
            addCriterion("bookoldprice <>", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceGreaterThan(Double value) {
            addCriterion("bookoldprice >", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("bookoldprice >=", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceLessThan(Double value) {
            addCriterion("bookoldprice <", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceLessThanOrEqualTo(Double value) {
            addCriterion("bookoldprice <=", value, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceIn(List<Double> values) {
            addCriterion("bookoldprice in", values, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceNotIn(List<Double> values) {
            addCriterion("bookoldprice not in", values, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceBetween(Double value1, Double value2) {
            addCriterion("bookoldprice between", value1, value2, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBookoldpriceNotBetween(Double value1, Double value2) {
            addCriterion("bookoldprice not between", value1, value2, "bookoldprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceIsNull() {
            addCriterion("booknewprice is null");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceIsNotNull() {
            addCriterion("booknewprice is not null");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceEqualTo(Double value) {
            addCriterion("booknewprice =", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceNotEqualTo(Double value) {
            addCriterion("booknewprice <>", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceGreaterThan(Double value) {
            addCriterion("booknewprice >", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("booknewprice >=", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceLessThan(Double value) {
            addCriterion("booknewprice <", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceLessThanOrEqualTo(Double value) {
            addCriterion("booknewprice <=", value, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceIn(List<Double> values) {
            addCriterion("booknewprice in", values, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceNotIn(List<Double> values) {
            addCriterion("booknewprice not in", values, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceBetween(Double value1, Double value2) {
            addCriterion("booknewprice between", value1, value2, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBooknewpriceNotBetween(Double value1, Double value2) {
            addCriterion("booknewprice not between", value1, value2, "booknewprice");
            return (Criteria) this;
        }

        public Criteria andBookauthorIsNull() {
            addCriterion("bookauthor is null");
            return (Criteria) this;
        }

        public Criteria andBookauthorIsNotNull() {
            addCriterion("bookauthor is not null");
            return (Criteria) this;
        }

        public Criteria andBookauthorEqualTo(String value) {
            addCriterion("bookauthor =", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorNotEqualTo(String value) {
            addCriterion("bookauthor <>", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorGreaterThan(String value) {
            addCriterion("bookauthor >", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorGreaterThanOrEqualTo(String value) {
            addCriterion("bookauthor >=", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorLessThan(String value) {
            addCriterion("bookauthor <", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorLessThanOrEqualTo(String value) {
            addCriterion("bookauthor <=", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorLike(String value) {
            addCriterion("bookauthor like", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorNotLike(String value) {
            addCriterion("bookauthor not like", value, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorIn(List<String> values) {
            addCriterion("bookauthor in", values, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorNotIn(List<String> values) {
            addCriterion("bookauthor not in", values, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorBetween(String value1, String value2) {
            addCriterion("bookauthor between", value1, value2, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookauthorNotBetween(String value1, String value2) {
            addCriterion("bookauthor not between", value1, value2, "bookauthor");
            return (Criteria) this;
        }

        public Criteria andBookclass1IsNull() {
            addCriterion("bookclass1 is null");
            return (Criteria) this;
        }

        public Criteria andBookclass1IsNotNull() {
            addCriterion("bookclass1 is not null");
            return (Criteria) this;
        }

        public Criteria andBookclass1EqualTo(String value) {
            addCriterion("bookclass1 =", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1NotEqualTo(String value) {
            addCriterion("bookclass1 <>", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1GreaterThan(String value) {
            addCriterion("bookclass1 >", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1GreaterThanOrEqualTo(String value) {
            addCriterion("bookclass1 >=", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1LessThan(String value) {
            addCriterion("bookclass1 <", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1LessThanOrEqualTo(String value) {
            addCriterion("bookclass1 <=", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1Like(String value) {
            addCriterion("bookclass1 like", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1NotLike(String value) {
            addCriterion("bookclass1 not like", value, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1In(List<String> values) {
            addCriterion("bookclass1 in", values, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1NotIn(List<String> values) {
            addCriterion("bookclass1 not in", values, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1Between(String value1, String value2) {
            addCriterion("bookclass1 between", value1, value2, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass1NotBetween(String value1, String value2) {
            addCriterion("bookclass1 not between", value1, value2, "bookclass1");
            return (Criteria) this;
        }

        public Criteria andBookclass2IsNull() {
            addCriterion("bookclass2 is null");
            return (Criteria) this;
        }

        public Criteria andBookclass2IsNotNull() {
            addCriterion("bookclass2 is not null");
            return (Criteria) this;
        }

        public Criteria andBookclass2EqualTo(String value) {
            addCriterion("bookclass2 =", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2NotEqualTo(String value) {
            addCriterion("bookclass2 <>", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2GreaterThan(String value) {
            addCriterion("bookclass2 >", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2GreaterThanOrEqualTo(String value) {
            addCriterion("bookclass2 >=", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2LessThan(String value) {
            addCriterion("bookclass2 <", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2LessThanOrEqualTo(String value) {
            addCriterion("bookclass2 <=", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2Like(String value) {
            addCriterion("bookclass2 like", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2NotLike(String value) {
            addCriterion("bookclass2 not like", value, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2In(List<String> values) {
            addCriterion("bookclass2 in", values, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2NotIn(List<String> values) {
            addCriterion("bookclass2 not in", values, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2Between(String value1, String value2) {
            addCriterion("bookclass2 between", value1, value2, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass2NotBetween(String value1, String value2) {
            addCriterion("bookclass2 not between", value1, value2, "bookclass2");
            return (Criteria) this;
        }

        public Criteria andBookclass3IsNull() {
            addCriterion("bookclass3 is null");
            return (Criteria) this;
        }

        public Criteria andBookclass3IsNotNull() {
            addCriterion("bookclass3 is not null");
            return (Criteria) this;
        }

        public Criteria andBookclass3EqualTo(String value) {
            addCriterion("bookclass3 =", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3NotEqualTo(String value) {
            addCriterion("bookclass3 <>", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3GreaterThan(String value) {
            addCriterion("bookclass3 >", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3GreaterThanOrEqualTo(String value) {
            addCriterion("bookclass3 >=", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3LessThan(String value) {
            addCriterion("bookclass3 <", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3LessThanOrEqualTo(String value) {
            addCriterion("bookclass3 <=", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3Like(String value) {
            addCriterion("bookclass3 like", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3NotLike(String value) {
            addCriterion("bookclass3 not like", value, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3In(List<String> values) {
            addCriterion("bookclass3 in", values, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3NotIn(List<String> values) {
            addCriterion("bookclass3 not in", values, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3Between(String value1, String value2) {
            addCriterion("bookclass3 between", value1, value2, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookclass3NotBetween(String value1, String value2) {
            addCriterion("bookclass3 not between", value1, value2, "bookclass3");
            return (Criteria) this;
        }

        public Criteria andBookpressIsNull() {
            addCriterion("bookpress is null");
            return (Criteria) this;
        }

        public Criteria andBookpressIsNotNull() {
            addCriterion("bookpress is not null");
            return (Criteria) this;
        }

        public Criteria andBookpressEqualTo(String value) {
            addCriterion("bookpress =", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotEqualTo(String value) {
            addCriterion("bookpress <>", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressGreaterThan(String value) {
            addCriterion("bookpress >", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressGreaterThanOrEqualTo(String value) {
            addCriterion("bookpress >=", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLessThan(String value) {
            addCriterion("bookpress <", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLessThanOrEqualTo(String value) {
            addCriterion("bookpress <=", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressLike(String value) {
            addCriterion("bookpress like", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotLike(String value) {
            addCriterion("bookpress not like", value, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressIn(List<String> values) {
            addCriterion("bookpress in", values, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotIn(List<String> values) {
            addCriterion("bookpress not in", values, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressBetween(String value1, String value2) {
            addCriterion("bookpress between", value1, value2, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpressNotBetween(String value1, String value2) {
            addCriterion("bookpress not between", value1, value2, "bookpress");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeIsNull() {
            addCriterion("bookpresstime is null");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeIsNotNull() {
            addCriterion("bookpresstime is not null");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeEqualTo(String value) {
            addCriterion("bookpresstime =", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeNotEqualTo(String value) {
            addCriterion("bookpresstime <>", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeGreaterThan(String value) {
            addCriterion("bookpresstime >", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeGreaterThanOrEqualTo(String value) {
            addCriterion("bookpresstime >=", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeLessThan(String value) {
            addCriterion("bookpresstime <", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeLessThanOrEqualTo(String value) {
            addCriterion("bookpresstime <=", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeLike(String value) {
            addCriterion("bookpresstime like", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeNotLike(String value) {
            addCriterion("bookpresstime not like", value, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeIn(List<String> values) {
            addCriterion("bookpresstime in", values, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeNotIn(List<String> values) {
            addCriterion("bookpresstime not in", values, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeBetween(String value1, String value2) {
            addCriterion("bookpresstime between", value1, value2, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBookpresstimeNotBetween(String value1, String value2) {
            addCriterion("bookpresstime not between", value1, value2, "bookpresstime");
            return (Criteria) this;
        }

        public Criteria andBooksizeIsNull() {
            addCriterion("booksize is null");
            return (Criteria) this;
        }

        public Criteria andBooksizeIsNotNull() {
            addCriterion("booksize is not null");
            return (Criteria) this;
        }

        public Criteria andBooksizeEqualTo(String value) {
            addCriterion("booksize =", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeNotEqualTo(String value) {
            addCriterion("booksize <>", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeGreaterThan(String value) {
            addCriterion("booksize >", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeGreaterThanOrEqualTo(String value) {
            addCriterion("booksize >=", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeLessThan(String value) {
            addCriterion("booksize <", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeLessThanOrEqualTo(String value) {
            addCriterion("booksize <=", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeLike(String value) {
            addCriterion("booksize like", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeNotLike(String value) {
            addCriterion("booksize not like", value, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeIn(List<String> values) {
            addCriterion("booksize in", values, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeNotIn(List<String> values) {
            addCriterion("booksize not in", values, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeBetween(String value1, String value2) {
            addCriterion("booksize between", value1, value2, "booksize");
            return (Criteria) this;
        }

        public Criteria andBooksizeNotBetween(String value1, String value2) {
            addCriterion("booksize not between", value1, value2, "booksize");
            return (Criteria) this;
        }

        public Criteria andBookimgIsNull() {
            addCriterion("bookimg is null");
            return (Criteria) this;
        }

        public Criteria andBookimgIsNotNull() {
            addCriterion("bookimg is not null");
            return (Criteria) this;
        }

        public Criteria andBookimgEqualTo(String value) {
            addCriterion("bookimg =", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgNotEqualTo(String value) {
            addCriterion("bookimg <>", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgGreaterThan(String value) {
            addCriterion("bookimg >", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgGreaterThanOrEqualTo(String value) {
            addCriterion("bookimg >=", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgLessThan(String value) {
            addCriterion("bookimg <", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgLessThanOrEqualTo(String value) {
            addCriterion("bookimg <=", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgLike(String value) {
            addCriterion("bookimg like", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgNotLike(String value) {
            addCriterion("bookimg not like", value, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgIn(List<String> values) {
            addCriterion("bookimg in", values, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgNotIn(List<String> values) {
            addCriterion("bookimg not in", values, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgBetween(String value1, String value2) {
            addCriterion("bookimg between", value1, value2, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookimgNotBetween(String value1, String value2) {
            addCriterion("bookimg not between", value1, value2, "bookimg");
            return (Criteria) this;
        }

        public Criteria andBookisbnIsNull() {
            addCriterion("bookisbn is null");
            return (Criteria) this;
        }

        public Criteria andBookisbnIsNotNull() {
            addCriterion("bookisbn is not null");
            return (Criteria) this;
        }

        public Criteria andBookisbnEqualTo(String value) {
            addCriterion("bookisbn =", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotEqualTo(String value) {
            addCriterion("bookisbn <>", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnGreaterThan(String value) {
            addCriterion("bookisbn >", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnGreaterThanOrEqualTo(String value) {
            addCriterion("bookisbn >=", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLessThan(String value) {
            addCriterion("bookisbn <", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLessThanOrEqualTo(String value) {
            addCriterion("bookisbn <=", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnLike(String value) {
            addCriterion("bookisbn like", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotLike(String value) {
            addCriterion("bookisbn not like", value, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnIn(List<String> values) {
            addCriterion("bookisbn in", values, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotIn(List<String> values) {
            addCriterion("bookisbn not in", values, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnBetween(String value1, String value2) {
            addCriterion("bookisbn between", value1, value2, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookisbnNotBetween(String value1, String value2) {
            addCriterion("bookisbn not between", value1, value2, "bookisbn");
            return (Criteria) this;
        }

        public Criteria andBookinfoIsNull() {
            addCriterion("bookinfo is null");
            return (Criteria) this;
        }

        public Criteria andBookinfoIsNotNull() {
            addCriterion("bookinfo is not null");
            return (Criteria) this;
        }

        public Criteria andBookinfoEqualTo(Integer value) {
            addCriterion("bookinfo =", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoNotEqualTo(Integer value) {
            addCriterion("bookinfo <>", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoGreaterThan(Integer value) {
            addCriterion("bookinfo >", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookinfo >=", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoLessThan(Integer value) {
            addCriterion("bookinfo <", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoLessThanOrEqualTo(Integer value) {
            addCriterion("bookinfo <=", value, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoIn(List<Integer> values) {
            addCriterion("bookinfo in", values, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoNotIn(List<Integer> values) {
            addCriterion("bookinfo not in", values, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoBetween(Integer value1, Integer value2) {
            addCriterion("bookinfo between", value1, value2, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBookinfoNotBetween(Integer value1, Integer value2) {
            addCriterion("bookinfo not between", value1, value2, "bookinfo");
            return (Criteria) this;
        }

        public Criteria andBook2class1IsNull() {
            addCriterion("book2class1 is null");
            return (Criteria) this;
        }

        public Criteria andBook2class1IsNotNull() {
            addCriterion("book2class1 is not null");
            return (Criteria) this;
        }

        public Criteria andBook2class1EqualTo(String value) {
            addCriterion("book2class1 =", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1NotEqualTo(String value) {
            addCriterion("book2class1 <>", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1GreaterThan(String value) {
            addCriterion("book2class1 >", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1GreaterThanOrEqualTo(String value) {
            addCriterion("book2class1 >=", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1LessThan(String value) {
            addCriterion("book2class1 <", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1LessThanOrEqualTo(String value) {
            addCriterion("book2class1 <=", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1Like(String value) {
            addCriterion("book2class1 like", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1NotLike(String value) {
            addCriterion("book2class1 not like", value, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1In(List<String> values) {
            addCriterion("book2class1 in", values, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1NotIn(List<String> values) {
            addCriterion("book2class1 not in", values, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1Between(String value1, String value2) {
            addCriterion("book2class1 between", value1, value2, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class1NotBetween(String value1, String value2) {
            addCriterion("book2class1 not between", value1, value2, "book2class1");
            return (Criteria) this;
        }

        public Criteria andBook2class2IsNull() {
            addCriterion("book2class2 is null");
            return (Criteria) this;
        }

        public Criteria andBook2class2IsNotNull() {
            addCriterion("book2class2 is not null");
            return (Criteria) this;
        }

        public Criteria andBook2class2EqualTo(String value) {
            addCriterion("book2class2 =", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2NotEqualTo(String value) {
            addCriterion("book2class2 <>", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2GreaterThan(String value) {
            addCriterion("book2class2 >", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2GreaterThanOrEqualTo(String value) {
            addCriterion("book2class2 >=", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2LessThan(String value) {
            addCriterion("book2class2 <", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2LessThanOrEqualTo(String value) {
            addCriterion("book2class2 <=", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2Like(String value) {
            addCriterion("book2class2 like", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2NotLike(String value) {
            addCriterion("book2class2 not like", value, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2In(List<String> values) {
            addCriterion("book2class2 in", values, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2NotIn(List<String> values) {
            addCriterion("book2class2 not in", values, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2Between(String value1, String value2) {
            addCriterion("book2class2 between", value1, value2, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class2NotBetween(String value1, String value2) {
            addCriterion("book2class2 not between", value1, value2, "book2class2");
            return (Criteria) this;
        }

        public Criteria andBook2class3IsNull() {
            addCriterion("book2class3 is null");
            return (Criteria) this;
        }

        public Criteria andBook2class3IsNotNull() {
            addCriterion("book2class3 is not null");
            return (Criteria) this;
        }

        public Criteria andBook2class3EqualTo(String value) {
            addCriterion("book2class3 =", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3NotEqualTo(String value) {
            addCriterion("book2class3 <>", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3GreaterThan(String value) {
            addCriterion("book2class3 >", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3GreaterThanOrEqualTo(String value) {
            addCriterion("book2class3 >=", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3LessThan(String value) {
            addCriterion("book2class3 <", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3LessThanOrEqualTo(String value) {
            addCriterion("book2class3 <=", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3Like(String value) {
            addCriterion("book2class3 like", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3NotLike(String value) {
            addCriterion("book2class3 not like", value, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3In(List<String> values) {
            addCriterion("book2class3 in", values, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3NotIn(List<String> values) {
            addCriterion("book2class3 not in", values, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3Between(String value1, String value2) {
            addCriterion("book2class3 between", value1, value2, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBook2class3NotBetween(String value1, String value2) {
            addCriterion("book2class3 not between", value1, value2, "book2class3");
            return (Criteria) this;
        }

        public Criteria andBookcountIsNull() {
            addCriterion("bookcount is null");
            return (Criteria) this;
        }

        public Criteria andBookcountIsNotNull() {
            addCriterion("bookcount is not null");
            return (Criteria) this;
        }

        public Criteria andBookcountEqualTo(Integer value) {
            addCriterion("bookcount =", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountNotEqualTo(Integer value) {
            addCriterion("bookcount <>", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountGreaterThan(Integer value) {
            addCriterion("bookcount >", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookcount >=", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountLessThan(Integer value) {
            addCriterion("bookcount <", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountLessThanOrEqualTo(Integer value) {
            addCriterion("bookcount <=", value, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountIn(List<Integer> values) {
            addCriterion("bookcount in", values, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountNotIn(List<Integer> values) {
            addCriterion("bookcount not in", values, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountBetween(Integer value1, Integer value2) {
            addCriterion("bookcount between", value1, value2, "bookcount");
            return (Criteria) this;
        }

        public Criteria andBookcountNotBetween(Integer value1, Integer value2) {
            addCriterion("bookcount not between", value1, value2, "bookcount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table book
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}