package com.zyx.mybookstore.Pojo;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cartid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer cartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.state
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cartid
     *
     * @return the value of cart.cartid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getCartid() {
        return cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cartid
     *
     * @param cartid the value for cart.cartid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setCartid(Integer cartid) {
        this.cartid = cartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.userid
     *
     * @return the value of cart.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.userid
     *
     * @param userid the value for cart.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.bookid
     *
     * @return the value of cart.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.bookid
     *
     * @param bookid the value for cart.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.bookcount
     *
     * @return the value of cart.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookcount() {
        return bookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.bookcount
     *
     * @param bookcount the value for cart.bookcount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookcount(Integer bookcount) {
        this.bookcount = bookcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.state
     *
     * @return the value of cart.state
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.state
     *
     * @param state the value for cart.state
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setState(String state) {
        this.state = state;
    }
}