package com.zyx.mybookstore.Pojo;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.citycode
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String citycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.cityname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String cityname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.citycode
     *
     * @return the value of city.citycode
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.citycode
     *
     * @param citycode the value for city.citycode
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.cityname
     *
     * @return the value of city.cityname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.cityname
     *
     * @param cityname the value for city.cityname
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }
}