package com.zyx.mybookstore.Pojo;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.classid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer classid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String class1name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class2name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String class2name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.class3name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String class3name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.classid
     *
     * @return the value of class.classid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.classid
     *
     * @param classid the value for class.classid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class1name
     *
     * @return the value of class.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getClass1name() {
        return class1name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class1name
     *
     * @param class1name the value for class.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setClass1name(String class1name) {
        this.class1name = class1name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class2name
     *
     * @return the value of class.class2name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getClass2name() {
        return class2name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class2name
     *
     * @param class2name the value for class.class2name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setClass2name(String class2name) {
        this.class2name = class2name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.class3name
     *
     * @return the value of class.class3name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getClass3name() {
        return class3name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.class3name
     *
     * @param class3name the value for class.class3name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setClass3name(String class3name) {
        this.class3name = class3name;
    }
}