package com.zyx.mybookstore.Pojo;

public class Consigneeinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private Integer consigneeinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.userid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.consigneename
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String consigneename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.consigneeadd
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String consigneeadd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.phone
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consigneeinfo.state
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.consigneeinfoid
     *
     * @return the value of consigneeinfo.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Integer getConsigneeinfoid() {
        return consigneeinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.consigneeinfoid
     *
     * @param consigneeinfoid the value for consigneeinfo.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setConsigneeinfoid(Integer consigneeinfoid) {
        this.consigneeinfoid = consigneeinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.userid
     *
     * @return the value of consigneeinfo.userid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.userid
     *
     * @param userid the value for consigneeinfo.userid
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.consigneename
     *
     * @return the value of consigneeinfo.consigneename
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getConsigneename() {
        return consigneename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.consigneename
     *
     * @param consigneename the value for consigneeinfo.consigneename
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setConsigneename(String consigneename) {
        this.consigneename = consigneename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.consigneeadd
     *
     * @return the value of consigneeinfo.consigneeadd
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getConsigneeadd() {
        return consigneeadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.consigneeadd
     *
     * @param consigneeadd the value for consigneeinfo.consigneeadd
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setConsigneeadd(String consigneeadd) {
        this.consigneeadd = consigneeadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.phone
     *
     * @return the value of consigneeinfo.phone
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.phone
     *
     * @param phone the value for consigneeinfo.phone
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consigneeinfo.state
     *
     * @return the value of consigneeinfo.state
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consigneeinfo.state
     *
     * @param state the value for consigneeinfo.state
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setState(String state) {
        this.state = state;
    }
}