package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ConsigneeinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public ConsigneeinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConsigneeinfoidIsNull() {
            addCriterion("consigneeinfoid is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidIsNotNull() {
            addCriterion("consigneeinfoid is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidEqualTo(Integer value) {
            addCriterion("consigneeinfoid =", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotEqualTo(Integer value) {
            addCriterion("consigneeinfoid <>", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidGreaterThan(Integer value) {
            addCriterion("consigneeinfoid >", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("consigneeinfoid >=", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidLessThan(Integer value) {
            addCriterion("consigneeinfoid <", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("consigneeinfoid <=", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidIn(List<Integer> values) {
            addCriterion("consigneeinfoid in", values, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotIn(List<Integer> values) {
            addCriterion("consigneeinfoid not in", values, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidBetween(Integer value1, Integer value2) {
            addCriterion("consigneeinfoid between", value1, value2, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("consigneeinfoid not between", value1, value2, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userid is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andConsigneenameIsNull() {
            addCriterion("consigneename is null");
            return (Criteria) this;
        }

        public Criteria andConsigneenameIsNotNull() {
            addCriterion("consigneename is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneenameEqualTo(String value) {
            addCriterion("consigneename =", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameNotEqualTo(String value) {
            addCriterion("consigneename <>", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameGreaterThan(String value) {
            addCriterion("consigneename >", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameGreaterThanOrEqualTo(String value) {
            addCriterion("consigneename >=", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameLessThan(String value) {
            addCriterion("consigneename <", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameLessThanOrEqualTo(String value) {
            addCriterion("consigneename <=", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameLike(String value) {
            addCriterion("consigneename like", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameNotLike(String value) {
            addCriterion("consigneename not like", value, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameIn(List<String> values) {
            addCriterion("consigneename in", values, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameNotIn(List<String> values) {
            addCriterion("consigneename not in", values, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameBetween(String value1, String value2) {
            addCriterion("consigneename between", value1, value2, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneenameNotBetween(String value1, String value2) {
            addCriterion("consigneename not between", value1, value2, "consigneename");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddIsNull() {
            addCriterion("consigneeadd is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddIsNotNull() {
            addCriterion("consigneeadd is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddEqualTo(String value) {
            addCriterion("consigneeadd =", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddNotEqualTo(String value) {
            addCriterion("consigneeadd <>", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddGreaterThan(String value) {
            addCriterion("consigneeadd >", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddGreaterThanOrEqualTo(String value) {
            addCriterion("consigneeadd >=", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddLessThan(String value) {
            addCriterion("consigneeadd <", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddLessThanOrEqualTo(String value) {
            addCriterion("consigneeadd <=", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddLike(String value) {
            addCriterion("consigneeadd like", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddNotLike(String value) {
            addCriterion("consigneeadd not like", value, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddIn(List<String> values) {
            addCriterion("consigneeadd in", values, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddNotIn(List<String> values) {
            addCriterion("consigneeadd not in", values, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddBetween(String value1, String value2) {
            addCriterion("consigneeadd between", value1, value2, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andConsigneeaddNotBetween(String value1, String value2) {
            addCriterion("consigneeadd not between", value1, value2, "consigneeadd");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consigneeinfo
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}