package com.zyx.mybookstore.Pojo;

public class Favortie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favortie.favortieid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer favortieid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favortie.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favortie.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favortie.favortiestate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String favortiestate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favortie.favortieid
     *
     * @return the value of favortie.favortieid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getFavortieid() {
        return favortieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favortie.favortieid
     *
     * @param favortieid the value for favortie.favortieid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFavortieid(Integer favortieid) {
        this.favortieid = favortieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favortie.userid
     *
     * @return the value of favortie.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favortie.userid
     *
     * @param userid the value for favortie.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favortie.bookid
     *
     * @return the value of favortie.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favortie.bookid
     *
     * @param bookid the value for favortie.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favortie.favortiestate
     *
     * @return the value of favortie.favortiestate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getFavortiestate() {
        return favortiestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favortie.favortiestate
     *
     * @param favortiestate the value for favortie.favortiestate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFavortiestate(String favortiestate) {
        this.favortiestate = favortiestate;
    }

    public Favortie(Integer userid, Integer bookid, String favortiestate) {
        this.userid = userid;
        this.bookid = bookid;
        this.favortiestate = favortiestate;
    }
}