package com.zyx.mybookstore.Pojo;

public class Feature {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature.featureid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer featureid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature.featuretype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String featuretype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feature.salecount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer salecount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature.featureid
     *
     * @return the value of feature.featureid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getFeatureid() {
        return featureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature.featureid
     *
     * @param featureid the value for feature.featureid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFeatureid(Integer featureid) {
        this.featureid = featureid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature.featuretype
     *
     * @return the value of feature.featuretype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getFeaturetype() {
        return featuretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature.featuretype
     *
     * @param featuretype the value for feature.featuretype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFeaturetype(String featuretype) {
        this.featuretype = featuretype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature.bookid
     *
     * @return the value of feature.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature.bookid
     *
     * @param bookid the value for feature.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feature.salecount
     *
     * @return the value of feature.salecount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getSalecount() {
        return salecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feature.salecount
     *
     * @param salecount the value for feature.salecount
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setSalecount(Integer salecount) {
        this.salecount = salecount;
    }
}