package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class FeatureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public FeatureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFeatureidIsNull() {
            addCriterion("featureid is null");
            return (Criteria) this;
        }

        public Criteria andFeatureidIsNotNull() {
            addCriterion("featureid is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureidEqualTo(Integer value) {
            addCriterion("featureid =", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotEqualTo(Integer value) {
            addCriterion("featureid <>", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidGreaterThan(Integer value) {
            addCriterion("featureid >", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidGreaterThanOrEqualTo(Integer value) {
            addCriterion("featureid >=", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidLessThan(Integer value) {
            addCriterion("featureid <", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidLessThanOrEqualTo(Integer value) {
            addCriterion("featureid <=", value, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidIn(List<Integer> values) {
            addCriterion("featureid in", values, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotIn(List<Integer> values) {
            addCriterion("featureid not in", values, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidBetween(Integer value1, Integer value2) {
            addCriterion("featureid between", value1, value2, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeatureidNotBetween(Integer value1, Integer value2) {
            addCriterion("featureid not between", value1, value2, "featureid");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeIsNull() {
            addCriterion("featuretype is null");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeIsNotNull() {
            addCriterion("featuretype is not null");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeEqualTo(String value) {
            addCriterion("featuretype =", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeNotEqualTo(String value) {
            addCriterion("featuretype <>", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeGreaterThan(String value) {
            addCriterion("featuretype >", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeGreaterThanOrEqualTo(String value) {
            addCriterion("featuretype >=", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeLessThan(String value) {
            addCriterion("featuretype <", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeLessThanOrEqualTo(String value) {
            addCriterion("featuretype <=", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeLike(String value) {
            addCriterion("featuretype like", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeNotLike(String value) {
            addCriterion("featuretype not like", value, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeIn(List<String> values) {
            addCriterion("featuretype in", values, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeNotIn(List<String> values) {
            addCriterion("featuretype not in", values, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeBetween(String value1, String value2) {
            addCriterion("featuretype between", value1, value2, "featuretype");
            return (Criteria) this;
        }

        public Criteria andFeaturetypeNotBetween(String value1, String value2) {
            addCriterion("featuretype not between", value1, value2, "featuretype");
            return (Criteria) this;
        }

        public Criteria andBookidIsNull() {
            addCriterion("bookid is null");
            return (Criteria) this;
        }

        public Criteria andBookidIsNotNull() {
            addCriterion("bookid is not null");
            return (Criteria) this;
        }

        public Criteria andBookidEqualTo(Integer value) {
            addCriterion("bookid =", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotEqualTo(Integer value) {
            addCriterion("bookid <>", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThan(Integer value) {
            addCriterion("bookid >", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bookid >=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThan(Integer value) {
            addCriterion("bookid <", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidLessThanOrEqualTo(Integer value) {
            addCriterion("bookid <=", value, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidIn(List<Integer> values) {
            addCriterion("bookid in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotIn(List<Integer> values) {
            addCriterion("bookid not in", values, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidBetween(Integer value1, Integer value2) {
            addCriterion("bookid between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andBookidNotBetween(Integer value1, Integer value2) {
            addCriterion("bookid not between", value1, value2, "bookid");
            return (Criteria) this;
        }

        public Criteria andSalecountIsNull() {
            addCriterion("salecount is null");
            return (Criteria) this;
        }

        public Criteria andSalecountIsNotNull() {
            addCriterion("salecount is not null");
            return (Criteria) this;
        }

        public Criteria andSalecountEqualTo(Integer value) {
            addCriterion("salecount =", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotEqualTo(Integer value) {
            addCriterion("salecount <>", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountGreaterThan(Integer value) {
            addCriterion("salecount >", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountGreaterThanOrEqualTo(Integer value) {
            addCriterion("salecount >=", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountLessThan(Integer value) {
            addCriterion("salecount <", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountLessThanOrEqualTo(Integer value) {
            addCriterion("salecount <=", value, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountIn(List<Integer> values) {
            addCriterion("salecount in", values, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotIn(List<Integer> values) {
            addCriterion("salecount not in", values, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountBetween(Integer value1, Integer value2) {
            addCriterion("salecount between", value1, value2, "salecount");
            return (Criteria) this;
        }

        public Criteria andSalecountNotBetween(Integer value1, Integer value2) {
            addCriterion("salecount not between", value1, value2, "salecount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feature
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feature
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}