package com.zyx.mybookstore.Pojo;

public class Footerprint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footerprint.footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer footerprint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footerprint.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footerprint.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column footerprint.footerprintstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String footerprintstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footerprint.footerprint
     *
     * @return the value of footerprint.footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getFooterprint() {
        return footerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footerprint.footerprint
     *
     * @param footerprint the value for footerprint.footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFooterprint(Integer footerprint) {
        this.footerprint = footerprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footerprint.userid
     *
     * @return the value of footerprint.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footerprint.userid
     *
     * @param userid the value for footerprint.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footerprint.bookname
     *
     * @return the value of footerprint.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footerprint.bookname
     *
     * @param bookname the value for footerprint.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column footerprint.footerprintstate
     *
     * @return the value of footerprint.footerprintstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getFooterprintstate() {
        return footerprintstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column footerprint.footerprintstate
     *
     * @param footerprintstate the value for footerprint.footerprintstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFooterprintstate(String footerprintstate) {
        this.footerprintstate = footerprintstate;
    }
}