package com.zyx.mybookstore.Pojo;

public class Hot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot.hotid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer hotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot.hotid
     *
     * @return the value of hot.hotid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getHotid() {
        return hotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot.hotid
     *
     * @param hotid the value for hot.hotid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setHotid(Integer hotid) {
        this.hotid = hotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot.bookid
     *
     * @return the value of hot.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot.bookid
     *
     * @param bookid the value for hot.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
}