package com.zyx.mybookstore.Pojo;

public class More {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column more.moreid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer moreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column more.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column more.moreid
     *
     * @return the value of more.moreid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getMoreid() {
        return moreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column more.moreid
     *
     * @param moreid the value for more.moreid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setMoreid(Integer moreid) {
        this.moreid = moreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column more.bookid
     *
     * @return the value of more.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column more.bookid
     *
     * @param bookid the value for more.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
}