package com.zyx.mybookstore.Pojo;

public class Newbook {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newbook.newbookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer newbookid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column newbook.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newbook.newbookid
     *
     * @return the value of newbook.newbookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getNewbookid() {
        return newbookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newbook.newbookid
     *
     * @param newbookid the value for newbook.newbookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setNewbookid(Integer newbookid) {
        this.newbookid = newbookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column newbook.bookid
     *
     * @return the value of newbook.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column newbook.bookid
     *
     * @param bookid the value for newbook.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
}