package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderidIsNull() {
            addCriterion("orderid is null");
            return (Criteria) this;
        }

        public Criteria andOrderidIsNotNull() {
            addCriterion("orderid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderidEqualTo(Integer value) {
            addCriterion("orderid =", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotEqualTo(Integer value) {
            addCriterion("orderid <>", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThan(Integer value) {
            addCriterion("orderid >", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderid >=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThan(Integer value) {
            addCriterion("orderid <", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidLessThanOrEqualTo(Integer value) {
            addCriterion("orderid <=", value, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidIn(List<Integer> values) {
            addCriterion("orderid in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotIn(List<Integer> values) {
            addCriterion("orderid not in", values, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidBetween(Integer value1, Integer value2) {
            addCriterion("orderid between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andOrderidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderid not between", value1, value2, "orderid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidIsNull() {
            addCriterion("consigneeinfoid is null");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidIsNotNull() {
            addCriterion("consigneeinfoid is not null");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidEqualTo(Integer value) {
            addCriterion("consigneeinfoid =", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotEqualTo(Integer value) {
            addCriterion("consigneeinfoid <>", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidGreaterThan(Integer value) {
            addCriterion("consigneeinfoid >", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("consigneeinfoid >=", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidLessThan(Integer value) {
            addCriterion("consigneeinfoid <", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidLessThanOrEqualTo(Integer value) {
            addCriterion("consigneeinfoid <=", value, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidIn(List<Integer> values) {
            addCriterion("consigneeinfoid in", values, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotIn(List<Integer> values) {
            addCriterion("consigneeinfoid not in", values, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidBetween(Integer value1, Integer value2) {
            addCriterion("consigneeinfoid between", value1, value2, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andConsigneeinfoidNotBetween(Integer value1, Integer value2) {
            addCriterion("consigneeinfoid not between", value1, value2, "consigneeinfoid");
            return (Criteria) this;
        }

        public Criteria andOrderremarkIsNull() {
            addCriterion("orderremark is null");
            return (Criteria) this;
        }

        public Criteria andOrderremarkIsNotNull() {
            addCriterion("orderremark is not null");
            return (Criteria) this;
        }

        public Criteria andOrderremarkEqualTo(String value) {
            addCriterion("orderremark =", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkNotEqualTo(String value) {
            addCriterion("orderremark <>", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkGreaterThan(String value) {
            addCriterion("orderremark >", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkGreaterThanOrEqualTo(String value) {
            addCriterion("orderremark >=", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkLessThan(String value) {
            addCriterion("orderremark <", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkLessThanOrEqualTo(String value) {
            addCriterion("orderremark <=", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkLike(String value) {
            addCriterion("orderremark like", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkNotLike(String value) {
            addCriterion("orderremark not like", value, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkIn(List<String> values) {
            addCriterion("orderremark in", values, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkNotIn(List<String> values) {
            addCriterion("orderremark not in", values, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkBetween(String value1, String value2) {
            addCriterion("orderremark between", value1, value2, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderremarkNotBetween(String value1, String value2) {
            addCriterion("orderremark not between", value1, value2, "orderremark");
            return (Criteria) this;
        }

        public Criteria andOrderpayIsNull() {
            addCriterion("orderpay is null");
            return (Criteria) this;
        }

        public Criteria andOrderpayIsNotNull() {
            addCriterion("orderpay is not null");
            return (Criteria) this;
        }

        public Criteria andOrderpayEqualTo(Double value) {
            addCriterion("orderpay =", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayNotEqualTo(Double value) {
            addCriterion("orderpay <>", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayGreaterThan(Double value) {
            addCriterion("orderpay >", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayGreaterThanOrEqualTo(Double value) {
            addCriterion("orderpay >=", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayLessThan(Double value) {
            addCriterion("orderpay <", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayLessThanOrEqualTo(Double value) {
            addCriterion("orderpay <=", value, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayIn(List<Double> values) {
            addCriterion("orderpay in", values, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayNotIn(List<Double> values) {
            addCriterion("orderpay not in", values, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayBetween(Double value1, Double value2) {
            addCriterion("orderpay between", value1, value2, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrderpayNotBetween(Double value1, Double value2) {
            addCriterion("orderpay not between", value1, value2, "orderpay");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIsNull() {
            addCriterion("ordernumber is null");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIsNotNull() {
            addCriterion("ordernumber is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernumberEqualTo(String value) {
            addCriterion("ordernumber =", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotEqualTo(String value) {
            addCriterion("ordernumber <>", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberGreaterThan(String value) {
            addCriterion("ordernumber >", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberGreaterThanOrEqualTo(String value) {
            addCriterion("ordernumber >=", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberLessThan(String value) {
            addCriterion("ordernumber <", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberLessThanOrEqualTo(String value) {
            addCriterion("ordernumber <=", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberLike(String value) {
            addCriterion("ordernumber like", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotLike(String value) {
            addCriterion("ordernumber not like", value, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberIn(List<String> values) {
            addCriterion("ordernumber in", values, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotIn(List<String> values) {
            addCriterion("ordernumber not in", values, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberBetween(String value1, String value2) {
            addCriterion("ordernumber between", value1, value2, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrdernumberNotBetween(String value1, String value2) {
            addCriterion("ordernumber not between", value1, value2, "ordernumber");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNull() {
            addCriterion("orderstate is null");
            return (Criteria) this;
        }

        public Criteria andOrderstateIsNotNull() {
            addCriterion("orderstate is not null");
            return (Criteria) this;
        }

        public Criteria andOrderstateEqualTo(String value) {
            addCriterion("orderstate =", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotEqualTo(String value) {
            addCriterion("orderstate <>", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThan(String value) {
            addCriterion("orderstate >", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateGreaterThanOrEqualTo(String value) {
            addCriterion("orderstate >=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThan(String value) {
            addCriterion("orderstate <", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLessThanOrEqualTo(String value) {
            addCriterion("orderstate <=", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateLike(String value) {
            addCriterion("orderstate like", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotLike(String value) {
            addCriterion("orderstate not like", value, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateIn(List<String> values) {
            addCriterion("orderstate in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotIn(List<String> values) {
            addCriterion("orderstate not in", values, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateBetween(String value1, String value2) {
            addCriterion("orderstate between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrderstateNotBetween(String value1, String value2) {
            addCriterion("orderstate not between", value1, value2, "orderstate");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNull() {
            addCriterion("ordertime is null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIsNotNull() {
            addCriterion("ordertime is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertimeEqualTo(String value) {
            addCriterion("ordertime =", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotEqualTo(String value) {
            addCriterion("ordertime <>", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThan(String value) {
            addCriterion("ordertime >", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeGreaterThanOrEqualTo(String value) {
            addCriterion("ordertime >=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThan(String value) {
            addCriterion("ordertime <", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLessThanOrEqualTo(String value) {
            addCriterion("ordertime <=", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeLike(String value) {
            addCriterion("ordertime like", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotLike(String value) {
            addCriterion("ordertime not like", value, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeIn(List<String> values) {
            addCriterion("ordertime in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotIn(List<String> values) {
            addCriterion("ordertime not in", values, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeBetween(String value1, String value2) {
            addCriterion("ordertime between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andOrdertimeNotBetween(String value1, String value2) {
            addCriterion("ordertime not between", value1, value2, "ordertime");
            return (Criteria) this;
        }

        public Criteria andPaystateIsNull() {
            addCriterion("paystate is null");
            return (Criteria) this;
        }

        public Criteria andPaystateIsNotNull() {
            addCriterion("paystate is not null");
            return (Criteria) this;
        }

        public Criteria andPaystateEqualTo(String value) {
            addCriterion("paystate =", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotEqualTo(String value) {
            addCriterion("paystate <>", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateGreaterThan(String value) {
            addCriterion("paystate >", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateGreaterThanOrEqualTo(String value) {
            addCriterion("paystate >=", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLessThan(String value) {
            addCriterion("paystate <", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLessThanOrEqualTo(String value) {
            addCriterion("paystate <=", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateLike(String value) {
            addCriterion("paystate like", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotLike(String value) {
            addCriterion("paystate not like", value, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateIn(List<String> values) {
            addCriterion("paystate in", values, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotIn(List<String> values) {
            addCriterion("paystate not in", values, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateBetween(String value1, String value2) {
            addCriterion("paystate between", value1, value2, "paystate");
            return (Criteria) this;
        }

        public Criteria andPaystateNotBetween(String value1, String value2) {
            addCriterion("paystate not between", value1, value2, "paystate");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoIsNull() {
            addCriterion("logisticsinfo is null");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoIsNotNull() {
            addCriterion("logisticsinfo is not null");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoEqualTo(String value) {
            addCriterion("logisticsinfo =", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoNotEqualTo(String value) {
            addCriterion("logisticsinfo <>", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoGreaterThan(String value) {
            addCriterion("logisticsinfo >", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoGreaterThanOrEqualTo(String value) {
            addCriterion("logisticsinfo >=", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoLessThan(String value) {
            addCriterion("logisticsinfo <", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoLessThanOrEqualTo(String value) {
            addCriterion("logisticsinfo <=", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoLike(String value) {
            addCriterion("logisticsinfo like", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoNotLike(String value) {
            addCriterion("logisticsinfo not like", value, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoIn(List<String> values) {
            addCriterion("logisticsinfo in", values, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoNotIn(List<String> values) {
            addCriterion("logisticsinfo not in", values, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoBetween(String value1, String value2) {
            addCriterion("logisticsinfo between", value1, value2, "logisticsinfo");
            return (Criteria) this;
        }

        public Criteria andLogisticsinfoNotBetween(String value1, String value2) {
            addCriterion("logisticsinfo not between", value1, value2, "logisticsinfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}