package com.zyx.mybookstore.Pojo;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer consigneeinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderremark
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String orderremark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderpay
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Double orderpay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordernumber
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String orderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordertime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.paystate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String paystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.logisticsinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String logisticsinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.isanonymous
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private byte[] isanonymous;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderid
     *
     * @return the value of orders.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderid
     *
     * @param orderid the value for orders.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.consigneeinfoid
     *
     * @return the value of orders.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getConsigneeinfoid() {
        return consigneeinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.consigneeinfoid
     *
     * @param consigneeinfoid the value for orders.consigneeinfoid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setConsigneeinfoid(Integer consigneeinfoid) {
        this.consigneeinfoid = consigneeinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderremark
     *
     * @return the value of orders.orderremark
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderremark() {
        return orderremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderremark
     *
     * @param orderremark the value for orders.orderremark
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderremark(String orderremark) {
        this.orderremark = orderremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderpay
     *
     * @return the value of orders.orderpay
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Double getOrderpay() {
        return orderpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderpay
     *
     * @param orderpay the value for orders.orderpay
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderpay(Double orderpay) {
        this.orderpay = orderpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordernumber
     *
     * @return the value of orders.ordernumber
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordernumber
     *
     * @param ordernumber the value for orders.ordernumber
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrdernumber(String ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderstate
     *
     * @return the value of orders.orderstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderstate
     *
     * @param orderstate the value for orders.orderstate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordertime
     *
     * @return the value of orders.ordertime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordertime
     *
     * @param ordertime the value for orders.ordertime
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrdertime(String ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.paystate
     *
     * @return the value of orders.paystate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.paystate
     *
     * @param paystate the value for orders.paystate
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPaystate(String paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.logisticsinfo
     *
     * @return the value of orders.logisticsinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getLogisticsinfo() {
        return logisticsinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.logisticsinfo
     *
     * @param logisticsinfo the value for orders.logisticsinfo
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setLogisticsinfo(String logisticsinfo) {
        this.logisticsinfo = logisticsinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.isanonymous
     *
     * @return the value of orders.isanonymous
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public byte[] getIsanonymous() {
        return isanonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.isanonymous
     *
     * @param isanonymous the value for orders.isanonymous
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setIsanonymous(byte[] isanonymous) {
        this.isanonymous = isanonymous;
    }
}