package com.zyx.mybookstore.Pojo;

public class Outtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outtype.outtypeid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer outtypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outtype.outtypename
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String outtypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outtype.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String class1name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column outtype.outtypenum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer outtypenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outtype.outtypeid
     *
     * @return the value of outtype.outtypeid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getOuttypeid() {
        return outtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outtype.outtypeid
     *
     * @param outtypeid the value for outtype.outtypeid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOuttypeid(Integer outtypeid) {
        this.outtypeid = outtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outtype.outtypename
     *
     * @return the value of outtype.outtypename
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOuttypename() {
        return outtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outtype.outtypename
     *
     * @param outtypename the value for outtype.outtypename
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOuttypename(String outtypename) {
        this.outtypename = outtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outtype.class1name
     *
     * @return the value of outtype.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getClass1name() {
        return class1name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outtype.class1name
     *
     * @param class1name the value for outtype.class1name
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setClass1name(String class1name) {
        this.class1name = class1name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column outtype.outtypenum
     *
     * @return the value of outtype.outtypenum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getOuttypenum() {
        return outtypenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column outtype.outtypenum
     *
     * @param outtypenum the value for outtype.outtypenum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOuttypenum(Integer outtypenum) {
        this.outtypenum = outtypenum;
    }
}