package com.zyx.mybookstore.Pojo;

import java.util.ArrayList;
import java.util.List;

public class OuttypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public OuttypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOuttypeidIsNull() {
            addCriterion("outtypeid is null");
            return (Criteria) this;
        }

        public Criteria andOuttypeidIsNotNull() {
            addCriterion("outtypeid is not null");
            return (Criteria) this;
        }

        public Criteria andOuttypeidEqualTo(Integer value) {
            addCriterion("outtypeid =", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidNotEqualTo(Integer value) {
            addCriterion("outtypeid <>", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidGreaterThan(Integer value) {
            addCriterion("outtypeid >", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("outtypeid >=", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidLessThan(Integer value) {
            addCriterion("outtypeid <", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidLessThanOrEqualTo(Integer value) {
            addCriterion("outtypeid <=", value, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidIn(List<Integer> values) {
            addCriterion("outtypeid in", values, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidNotIn(List<Integer> values) {
            addCriterion("outtypeid not in", values, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidBetween(Integer value1, Integer value2) {
            addCriterion("outtypeid between", value1, value2, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("outtypeid not between", value1, value2, "outtypeid");
            return (Criteria) this;
        }

        public Criteria andOuttypenameIsNull() {
            addCriterion("outtypename is null");
            return (Criteria) this;
        }

        public Criteria andOuttypenameIsNotNull() {
            addCriterion("outtypename is not null");
            return (Criteria) this;
        }

        public Criteria andOuttypenameEqualTo(String value) {
            addCriterion("outtypename =", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameNotEqualTo(String value) {
            addCriterion("outtypename <>", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameGreaterThan(String value) {
            addCriterion("outtypename >", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameGreaterThanOrEqualTo(String value) {
            addCriterion("outtypename >=", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameLessThan(String value) {
            addCriterion("outtypename <", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameLessThanOrEqualTo(String value) {
            addCriterion("outtypename <=", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameLike(String value) {
            addCriterion("outtypename like", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameNotLike(String value) {
            addCriterion("outtypename not like", value, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameIn(List<String> values) {
            addCriterion("outtypename in", values, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameNotIn(List<String> values) {
            addCriterion("outtypename not in", values, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameBetween(String value1, String value2) {
            addCriterion("outtypename between", value1, value2, "outtypename");
            return (Criteria) this;
        }

        public Criteria andOuttypenameNotBetween(String value1, String value2) {
            addCriterion("outtypename not between", value1, value2, "outtypename");
            return (Criteria) this;
        }

        public Criteria andClass1nameIsNull() {
            addCriterion("class1name is null");
            return (Criteria) this;
        }

        public Criteria andClass1nameIsNotNull() {
            addCriterion("class1name is not null");
            return (Criteria) this;
        }

        public Criteria andClass1nameEqualTo(String value) {
            addCriterion("class1name =", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameNotEqualTo(String value) {
            addCriterion("class1name <>", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameGreaterThan(String value) {
            addCriterion("class1name >", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameGreaterThanOrEqualTo(String value) {
            addCriterion("class1name >=", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameLessThan(String value) {
            addCriterion("class1name <", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameLessThanOrEqualTo(String value) {
            addCriterion("class1name <=", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameLike(String value) {
            addCriterion("class1name like", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameNotLike(String value) {
            addCriterion("class1name not like", value, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameIn(List<String> values) {
            addCriterion("class1name in", values, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameNotIn(List<String> values) {
            addCriterion("class1name not in", values, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameBetween(String value1, String value2) {
            addCriterion("class1name between", value1, value2, "class1name");
            return (Criteria) this;
        }

        public Criteria andClass1nameNotBetween(String value1, String value2) {
            addCriterion("class1name not between", value1, value2, "class1name");
            return (Criteria) this;
        }

        public Criteria andOuttypenumIsNull() {
            addCriterion("outtypenum is null");
            return (Criteria) this;
        }

        public Criteria andOuttypenumIsNotNull() {
            addCriterion("outtypenum is not null");
            return (Criteria) this;
        }

        public Criteria andOuttypenumEqualTo(Integer value) {
            addCriterion("outtypenum =", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumNotEqualTo(Integer value) {
            addCriterion("outtypenum <>", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumGreaterThan(Integer value) {
            addCriterion("outtypenum >", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumGreaterThanOrEqualTo(Integer value) {
            addCriterion("outtypenum >=", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumLessThan(Integer value) {
            addCriterion("outtypenum <", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumLessThanOrEqualTo(Integer value) {
            addCriterion("outtypenum <=", value, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumIn(List<Integer> values) {
            addCriterion("outtypenum in", values, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumNotIn(List<Integer> values) {
            addCriterion("outtypenum not in", values, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumBetween(Integer value1, Integer value2) {
            addCriterion("outtypenum between", value1, value2, "outtypenum");
            return (Criteria) this;
        }

        public Criteria andOuttypenumNotBetween(Integer value1, Integer value2) {
            addCriterion("outtypenum not between", value1, value2, "outtypenum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outtype
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table outtype
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}