package com.zyx.mybookstore.Pojo;

public class Personcenter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.personcenterid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer personcenterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.favortienum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer favortienum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.intergral
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer intergral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.bookcoin
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookcoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.footprintnum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer footprintnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personcenter.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer orderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.personcenterid
     *
     * @return the value of personcenter.personcenterid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getPersoncenterid() {
        return personcenterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.personcenterid
     *
     * @param personcenterid the value for personcenter.personcenterid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPersoncenterid(Integer personcenterid) {
        this.personcenterid = personcenterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.userid
     *
     * @return the value of personcenter.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.userid
     *
     * @param userid the value for personcenter.userid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.favortienum
     *
     * @return the value of personcenter.favortienum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getFavortienum() {
        return favortienum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.favortienum
     *
     * @param favortienum the value for personcenter.favortienum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFavortienum(Integer favortienum) {
        this.favortienum = favortienum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.intergral
     *
     * @return the value of personcenter.intergral
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getIntergral() {
        return intergral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.intergral
     *
     * @param intergral the value for personcenter.intergral
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setIntergral(Integer intergral) {
        this.intergral = intergral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.bookcoin
     *
     * @return the value of personcenter.bookcoin
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookcoin() {
        return bookcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.bookcoin
     *
     * @param bookcoin the value for personcenter.bookcoin
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookcoin(Integer bookcoin) {
        this.bookcoin = bookcoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.footprintnum
     *
     * @return the value of personcenter.footprintnum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getFootprintnum() {
        return footprintnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.footprintnum
     *
     * @param footprintnum the value for personcenter.footprintnum
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setFootprintnum(Integer footprintnum) {
        this.footprintnum = footprintnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personcenter.orderid
     *
     * @return the value of personcenter.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personcenter.orderid
     *
     * @param orderid the value for personcenter.orderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }
}