package com.zyx.mybookstore.Pojo;

public class Press {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column press.pressid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer pressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column press.pressname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String pressname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column press.pressimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String pressimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column press.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String bookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column press.pressbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private String pressbrief;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column press.pressid
     *
     * @return the value of press.pressid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getPressid() {
        return pressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column press.pressid
     *
     * @param pressid the value for press.pressid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPressid(Integer pressid) {
        this.pressid = pressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column press.pressname
     *
     * @return the value of press.pressname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getPressname() {
        return pressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column press.pressname
     *
     * @param pressname the value for press.pressname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPressname(String pressname) {
        this.pressname = pressname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column press.pressimg
     *
     * @return the value of press.pressimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getPressimg() {
        return pressimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column press.pressimg
     *
     * @param pressimg the value for press.pressimg
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPressimg(String pressimg) {
        this.pressimg = pressimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column press.bookname
     *
     * @return the value of press.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column press.bookname
     *
     * @param bookname the value for press.bookname
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column press.pressbrief
     *
     * @return the value of press.pressbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public String getPressbrief() {
        return pressbrief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column press.pressbrief
     *
     * @param pressbrief the value for press.pressbrief
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setPressbrief(String pressbrief) {
        this.pressbrief = pressbrief;
    }
}