package com.zyx.mybookstore.Pojo;

public class Slider {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slider.sliderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer sliderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slider.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    private Integer bookid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slider.sliderid
     *
     * @return the value of slider.sliderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getSliderid() {
        return sliderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slider.sliderid
     *
     * @param sliderid the value for slider.sliderid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setSliderid(Integer sliderid) {
        this.sliderid = sliderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slider.bookid
     *
     * @return the value of slider.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public Integer getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slider.bookid
     *
     * @param bookid the value for slider.bookid
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    public void setBookid(Integer bookid) {
        this.bookid = bookid;
    }
}