package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Authortest;
import com.zyx.mybookstore.Pojo.AuthortestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthortestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    long countByExample(AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int deleteByExample(AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int deleteByPrimaryKey(Integer authortestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int insert(Authortest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int insertSelective(Authortest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    List<Authortest> selectByExampleWithBLOBs(AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    List<Authortest> selectByExample(AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    Authortest selectByPrimaryKey(Integer authortestid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Authortest record, @Param("example") AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Authortest record, @Param("example") AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByExample(@Param("record") Authortest record, @Param("example") AuthortestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByPrimaryKeySelective(Authortest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Authortest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authortest
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByPrimaryKey(Authortest record);
}