package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Consigneeinfo;
import com.zyx.mybookstore.Pojo.ConsigneeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsigneeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    long countByExample(ConsigneeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int deleteByExample(ConsigneeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int deleteByPrimaryKey(Integer consigneeinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int insert(Consigneeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int insertSelective(Consigneeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    List<Consigneeinfo> selectByExample(ConsigneeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    Consigneeinfo selectByPrimaryKey(Integer consigneeinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Consigneeinfo record, @Param("example") ConsigneeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByExample(@Param("record") Consigneeinfo record, @Param("example") ConsigneeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByPrimaryKeySelective(Consigneeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consigneeinfo
     *
     * @mbg.generated Thu Sep 05 18:11:45 CST 2019
     */
    int updateByPrimaryKey(Consigneeinfo record);
}