package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Favortie;
import com.zyx.mybookstore.Pojo.FavortieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FavortieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(FavortieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(FavortieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByPrimaryKey(Integer favortieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Favortie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Favortie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Favortie> selectByExample(FavortieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    Favortie selectByPrimaryKey(Integer favortieid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Favortie record, @Param("example") FavortieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Favortie record, @Param("example") FavortieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeySelective(Favortie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favortie
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKey(Favortie record);
}