package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Footerprint;
import com.zyx.mybookstore.Pojo.FooterprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FooterprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(FooterprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(FooterprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Footerprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Footerprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Footerprint> selectByExample(FooterprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Footerprint record, @Param("example") FooterprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table footerprint
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Footerprint record, @Param("example") FooterprintExample example);
}