package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Hot;
import com.zyx.mybookstore.Pojo.HotExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(HotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(HotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByPrimaryKey(Integer hotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Hot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Hot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Hot> selectByExample(HotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    Hot selectByPrimaryKey(Integer hotid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Hot record, @Param("example") HotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Hot record, @Param("example") HotExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeySelective(Hot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hot
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKey(Hot record);
}