package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Personcenter;
import com.zyx.mybookstore.Pojo.PersoncenterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersoncenterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(PersoncenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(PersoncenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByPrimaryKey(Integer personcenterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Personcenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Personcenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Personcenter> selectByExample(PersoncenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    Personcenter selectByPrimaryKey(Integer personcenterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Personcenter record, @Param("example") PersoncenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Personcenter record, @Param("example") PersoncenterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeySelective(Personcenter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcenter
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKey(Personcenter record);
}