package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Press;
import com.zyx.mybookstore.Pojo.PressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByPrimaryKey(Integer pressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Press record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Press record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Press> selectByExampleWithBLOBs(PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Press> selectByExample(PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    Press selectByPrimaryKey(Integer pressid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Press record, @Param("example") PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Press record, @Param("example") PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Press record, @Param("example") PressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeySelective(Press record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Press record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table press
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKey(Press record);
}