package com.zyx.mybookstore.Mapper;

import com.zyx.mybookstore.Pojo.Slider;
import com.zyx.mybookstore.Pojo.SliderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SliderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    long countByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int deleteByPrimaryKey(Integer sliderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insert(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int insertSelective(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    List<Slider> selectByExample(SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    Slider selectByPrimaryKey(Integer sliderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Slider record, @Param("example") SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByExample(@Param("record") Slider record, @Param("example") SliderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKeySelective(Slider record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slider
     *
     * @mbg.generated Thu Sep 05 18:11:44 CST 2019
     */
    int updateByPrimaryKey(Slider record);
}